DELETE FROM FRIENDSHIPS;
DELETE FROM FRIENDSHIP_STATUSES;
DELETE FROM RATINGS;

INSERT INTO FRIENDSHIP_STATUSES (id, name)
VALUES (1, 'PENDING');

INSERT INTO FRIENDSHIP_STATUSES (id, name)
VALUES (2, 'CONFIRMED');

INSERT INTO RATINGS (id, name)
VALUES (1, 'G');

INSERT INTO RATINGS (id, name)
VALUES (2, 'PG');

INSERT INTO RATINGS (id, name)
VALUES (3, 'PG13');

INSERT INTO RATINGS (id, name)
VALUES (4, 'R');

INSERT INTO RATINGS (id, name)
VALUES (5, 'NC17');